local p = require("oldworld.palette")

return {
    BlinkCmpMenu = { fg = p.fg, bg = p.bg },
    BlinkCmpMenuBorder = { fg = p.border, bg = p.bg },
    BlinkCmpMenuSelection = { bg = p.selection, fg = p.muted_purple },
    BlinkCmpDoc = { fg = p.fg, bg = p.bg },
    BlinkCmpDocBorder = { fg = p.border, bg = p.bg },
    BlinkCmpDocSeparator = { fg = p.subtext2, bg = p.bg },
    BlinkCmpSignatureHelp = { fg = p.fg, bg = p.bg },
    BlinkCmpSignatureHelpBorder = { fg = p.border, bg = p.bg },
    BlinkCmpKindText = { fg = p.muted_purple },
    BlinkCmpKindMethod = { fg = p.kind_purple },
    BlinkCmpKindFunction = { fg = p.kind_purple },
    BlinkCmpKindConstructor = { fg = p.magenta },
    BlinkCmpKindField = { fg = p.kind_green },
    BlinkCmpKindVariable = { fg = p.kind_green },
    BlinkCmpKindClass = { fg = p.kind_gold },
    BlinkCmpKindInterface = { fg = p.kind_gold },
    BlinkCmpKindModule = { fg = p.muted_purple },
    BlinkCmpKindProperty = { fg = p.kind_green },
    BlinkCmpKindUnit = { fg = p.muted_purple },
    BlinkCmpKindValue = { fg = p.magenta },
    BlinkCmpKindEnum = { fg = p.kind_gold },
    BlinkCmpKindKeyword = { fg = p.magenta },
    BlinkCmpKindSnippet = { fg = p.kind_green },
    BlinkCmpKindColor = { fg = p.magenta },
    BlinkCmpKindFile = { fg = p.muted_purple },
    BlinkCmpKindReference = { fg = p.muted_purple },
    BlinkCmpKindFolder = { fg = p.muted_purple },
    BlinkCmpKindEnumMember = { fg = p.kind_green },
    BlinkCmpKindConstant = { fg = p.magenta },
    BlinkCmpKindStruct = { fg = p.kind_gold },
    BlinkCmpKindEvent = { fg = p.magenta },
    BlinkCmpKindOperator = { fg = p.muted_purple },
    BlinkCmpKindTypeParameter = { fg = p.kind_gold },
}
